"""Fix typo in Transaction model amount column

Revision ID: 07ccb2768bcc
Revises: d3413bfca2d4
Create Date: 2025-07-14 19:35:15.450613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ccb2768bcc'
down_revision: Union[str, Sequence[str], None] = 'd3413bfca2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount', sa.Integer(), nullable=True))
    op.drop_column('transactions', 'ammount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('ammount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'amount')
    # ### end Alembic commands ###
