"""empty message

Revision ID: 09c30b65842b
Revises: 49af8d9b5eb0
Create Date: 2025-07-17 15:18:27.461307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09c30b65842b'
down_revision: Union[str, Sequence[str], None] = '49af8d9b5eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('successfull', 'pending', 'failed', name='trans_status'),
               nullable=True)
    op.alter_column('transactions', 'merchant_request_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('transactions', 'merchant_checkout_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'merchant_checkout_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('transactions', 'merchant_request_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('successfull', 'pending', 'failed', name='trans_status'),
               nullable=False)
    # ### end Alembic commands ###
