"""empty message

Revision ID: 1fe3a5d18f50
Revises: 6e67dda3c49b
Create Date: 2026-02-02 23:57:44.452825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe3a5d18f50'
down_revision: Union[str, Sequence[str], None] = '6e67dda3c49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_name')
    )
    op.create_index(op.f('ix_admin_admin_id'), 'admin', ['admin_id'], unique=False)
    # Add the column as nullable first
    op.add_column('stakes', sa.Column('public', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute('UPDATE stakes SET public = TRUE')
    # Now alter the column to be non-nullable
    op.alter_column('stakes', 'public', nullable=False, server_default=sa.true())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stakes', 'public')
    op.drop_index(op.f('ix_admin_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
