"""empty message

Revision ID: 1ff6e719a156
Revises: 722f37476a68
Create Date: 2026-04-14 21:05:20.108042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff6e719a156'
down_revision: Union[str, Sequence[str], None] = '722f37476a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_markets', sa.Column('option', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_markets', 'option')
    # ### end Alembic commands ###
