"""empty message

Revision ID: 2927ff84ab46
Revises: 7f0e5bf68c07
Create Date: 2025-10-21 12:52:12.618335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2927ff84ab46'
down_revision: Union[str, Sequence[str], None] = '7f0e5bf68c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixtures', 'home_score',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='home_score::integer',
               existing_nullable=True)
    op.alter_column('fixtures', 'away_score',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='away_score::integer',
               existing_nullable=True)
    op.add_column('popular_leagues', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('popular_leagues', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('popular_leagues', 'updated_at')
    op.drop_column('popular_leagues', 'created_at')
    op.alter_column('fixtures', 'away_score',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('fixtures', 'home_score',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
