"""empty message

Revision ID: 53825a2118a1
Revises: 84b737164a44
Create Date: 2025-11-05 19:48:16.199700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53825a2118a1'
down_revision: Union[str, Sequence[str], None] = '84b737164a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    op.execute("CREATE TYPE fixturestatus AS ENUM ('live', 'future', 'expired')")
    # Then add the column with the enum type
    op.add_column('fixtures', sa.Column('fixture_status', sa.Enum('live', 'future', 'expired', name='fixturestatus', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'fixture_status')
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS fixturestatus")
    # ### end Alembic commands ###
