"""empty message

Revision ID: 54408348aafe
Revises: 89ff866950d3
Create Date: 2026-04-03 23:14:06.995440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54408348aafe'
down_revision: Union[str, Sequence[str], None] = '89ff866950d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool_stakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('stake_status', sa.Enum('active', 'locked', 'resolved', name='poolstakestatus'), nullable=False),
    sa.Column('locks_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_date', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.Enum('home', 'away', 'draw', name='poolstakechoice'), nullable=True),
    sa.Column('pool_amount', sa.Integer(), nullable=False),
    sa.Column('home_pool', sa.Integer(), nullable=False),
    sa.Column('away_pool', sa.Integer(), nullable=False),
    sa.Column('draw_pool', sa.Integer(), nullable=False),
    sa.Column('home_pool_count', sa.Integer(), nullable=False),
    sa.Column('away_pool_count', sa.Integer(), nullable=False),
    sa.Column('draw_pool_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.local_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['fixtures.local_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_stakes_id'), 'pool_stakes', ['id'], unique=False)
    op.create_table('unique_stakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('stake_statement', sa.String(), nullable=False),
    sa.Column('stake_type', sa.Enum('match_based', 'event_based', name='uniquestaketype'), nullable=False),
    sa.Column('stake_status', sa.Enum('pending_approval', 'active', 'locked', 'resolved', 'rejected', 'cancelled', name='uniquestakestatus'), nullable=False),
    sa.Column('locks_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_date', sa.DateTime(), nullable=True),
    sa.Column('resolution_source', sa.String(), nullable=True),
    sa.Column('outcome', sa.Enum('yes', 'no', 'draw', name='uniquestakechoice'), nullable=True),
    sa.Column('outcome_notes', sa.String(), nullable=True),
    sa.Column('admin_notes', sa.String(), nullable=True),
    sa.Column('pool_amount', sa.Integer(), nullable=False),
    sa.Column('yes_pool', sa.Integer(), nullable=False),
    sa.Column('no_pool', sa.Integer(), nullable=False),
    sa.Column('draw_pool', sa.Integer(), nullable=True),
    sa.Column('yes_count', sa.Integer(), nullable=False),
    sa.Column('no_count', sa.Integer(), nullable=False),
    sa.Column('draw_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.local_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['fixtures.local_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unique_stakes_id'), 'unique_stakes', ['id'], unique=False)
    op.create_table('pool_stake_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_stake_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('placement', sa.Enum('home', 'away', 'draw', name='poolstakechoice'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payout_amount', sa.Integer(), nullable=True),
    sa.Column('possible_win', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pool_stake_id'], ['pool_stakes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_stake_entries_id'), 'pool_stake_entries', ['id'], unique=False)
    op.create_table('unique_stake_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_stake_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('placement', sa.Enum('yes', 'no', 'draw', name='uniquestakechoice'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payout_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'refunded', name='uniquestakeentrystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unique_stake_id'], ['unique_stakes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unique_stake_entries_id'), 'unique_stake_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unique_stake_entries_id'), table_name='unique_stake_entries')
    op.drop_table('unique_stake_entries')
    op.drop_index(op.f('ix_pool_stake_entries_id'), table_name='pool_stake_entries')
    op.drop_table('pool_stake_entries')
    op.drop_index(op.f('ix_unique_stakes_id'), table_name='unique_stakes')
    op.drop_table('unique_stakes')
    op.drop_index(op.f('ix_pool_stakes_id'), table_name='pool_stakes')
    op.drop_table('pool_stakes')
    # ### end Alembic commands ###
