"""empty message

Revision ID: 5791d46bcf9a
Revises: b041f448c368
Create Date: 2026-04-12 19:43:38.027799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5791d46bcf9a'
down_revision: Union[str, Sequence[str], None] = 'b041f448c368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_markets', sa.Column('featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_markets', 'featured')
    # ### end Alembic commands ###
