"""empty message

Revision ID: 60f3357e41e8
Revises: ae965fea1bf5
Create Date: 2026-06-01 20:39:40.505275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60f3357e41e8'
down_revision: Union[str, Sequence[str], None] = 'ae965fea1bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pool_stake_entries_id'), table_name='pool_stake_entries')
    op.drop_table('pool_stake_entries')
    op.drop_index(op.f('ix_pool_stakes_id'), table_name='pool_stakes')
    op.drop_table('pool_stakes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool_stakes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pool_stakes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stake_status', postgresql.ENUM('active', 'locked', 'resolved', name='poolstakestatus'), autoincrement=False, nullable=False),
    sa.Column('locks_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolution_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('outcome', postgresql.ENUM('home', 'away', 'draw', name='poolstakechoice'), autoincrement=False, nullable=True),
    sa.Column('pool_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_pool', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_pool', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('draw_pool', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_pool_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_pool_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('draw_pool_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.local_id'], name='pool_stakes_league_id_fkey'),
    sa.ForeignKeyConstraint(['match_id'], ['fixtures.local_id'], name='pool_stakes_match_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pool_stakes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_pool_stakes_id'), 'pool_stakes', ['id'], unique=False)
    op.create_table('pool_stake_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pool_stake_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('placement', postgresql.ENUM('home', 'away', 'draw', name='poolstakechoice'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payout_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pool_stake_id'], ['pool_stakes.id'], name=op.f('pool_stake_entries_pool_stake_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('pool_stake_entries_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pool_stake_entries_pkey'))
    )
    op.create_index(op.f('ix_pool_stake_entries_id'), 'pool_stake_entries', ['id'], unique=False)
    # ### end Alembic commands ###
