"""empty message

Revision ID: 626cba678274
Revises: 83fdb5972d04
Create Date: 2025-07-30 14:23:40.122578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626cba678274'
down_revision: Union[str, Sequence[str], None] = '83fdb5972d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chess_profile_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('country', sa.Enum('KE', name='country_code'), nullable=True),
    sa.Column('account_status', sa.Enum('basic', name='account_status_code'), nullable=True),
    sa.Column('account_verification_status', sa.Boolean(), nullable=True),
    sa.Column('league', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_chess_profile_table_id'), 'chess_profile_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chess_profile_table_id'), table_name='chess_profile_table')
    op.drop_table('chess_profile_table')
    # ### end Alembic commands ###
