"""empty message

Revision ID: 66bfd32a0d56
Revises: 53825a2118a1
Create Date: 2025-11-10 09:21:53.793735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66bfd32a0d56'
down_revision: Union[str, Sequence[str], None] = '53825a2118a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stakes', sa.Column('possibleWin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stakes', 'possibleWin')
    # ### end Alembic commands ###
