"""empty message

Revision ID: 6e67dda3c49b
Revises: c6ef9ddb5bde
Create Date: 2025-12-11 10:54:10.956484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e67dda3c49b'
down_revision: Union[str, Sequence[str], None] = 'c6ef9ddb5bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'none' value to the stakewinner enum
    op.execute("ALTER TYPE stakewinner ADD VALUE IF NOT EXISTS 'none'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
