"""empty message

Revision ID: 7111eede02cd
Revises: b1845e10c916
Create Date: 2026-02-11 20:14:03.222983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7111eede02cd'
down_revision: Union[str, Sequence[str], None] = 'b1845e10c916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fixtures_team_id_fkey'), 'fixtures', type_='foreignkey')
    op.drop_column('fixtures', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fixtures_team_id_fkey'), 'fixtures', 'teams', ['team_id'], ['local_id'])
    # ### end Alembic commands ###
