"""empty message

Revision ID: 722f37476a68
Revises: d6bf4c825a4e
Create Date: 2026-04-13 00:38:34.861417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '722f37476a68'
down_revision: Union[str, Sequence[str], None] = 'd6bf4c825a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First ensure the target enum exists (it should from prediction markets)
    predictionmarketstatus_enum = postgresql.ENUM('pending_approval', 'active', 'locked', 'resolved', 'rejected', 'cancelled', name='predictionmarketstatus')
    predictionmarketstatus_enum.create(op.get_bind())
    
    # Convert the column using explicit casting
    op.execute("ALTER TABLE fixture_based_markets ALTER COLUMN market_status TYPE predictionmarketstatus USING market_status::text::predictionmarketstatus")
    
    # Drop the old enum
    op.execute("DROP TYPE IF EXISTS fixturebasedmarketstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the old enum
    fixturebasedmarketstatus_enum = postgresql.ENUM('pending_approval', 'active', 'locked', 'resolved', 'rejected', 'cancelled', name='fixturebasedmarketstatus')
    fixturebasedmarketstatus_enum.create(op.get_bind())
    
    # Convert back to the old enum
    op.execute("ALTER TABLE fixture_based_markets ALTER COLUMN market_status TYPE fixturebasedmarketstatus USING market_status::text::fixturebasedmarketstatus")
    
    # Drop the predictionmarketstatus enum (only if no other tables use it)
    # Note: Be careful with this in production if other tables use predictionmarketstatus
    # op.execute("DROP TYPE IF EXISTS predictionmarketstatus")
    # ### end Alembic commands ###
