"""empty message

Revision ID: 83fdb5972d04
Revises: 09c30b65842b
Create Date: 2025-07-21 11:11:02.710840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fdb5972d04'
down_revision: Union[str, Sequence[str], None] = '09c30b65842b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('ConversationID', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('OriginatorConversationID', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'OriginatorConversationID')
    op.drop_column('transactions', 'ConversationID')
    # ### end Alembic commands ###
