"""empty message

Revision ID: a55cd38ae7a9
Revises: 47c791f7653b
Create Date: 2026-04-07 00:16:52.217984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a55cd38ae7a9'
down_revision: Union[str, Sequence[str], None] = '47c791f7653b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('b', sa.Float(), nullable=False),
    sa.Column('q_yes', sa.Float(), nullable=False),
    sa.Column('q_no', sa.Float(), nullable=False),
    sa.Column('total_collected', sa.Float(), nullable=False),
    sa.Column('house_reserve', sa.Float(), nullable=False),
    sa.Column('market_status', sa.Enum('pending_approval', 'active', 'locked', 'resolved', 'rejected', 'cancelled', name='predictionmarketstatus'), nullable=False),
    sa.Column('locks_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_date', sa.DateTime(), nullable=True),
    sa.Column('resolution_source', sa.String(), nullable=True),
    sa.Column('outcome', sa.Enum('yes', 'no', name='predictionmarketoutcome'), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_markets_id'), 'prediction_markets', ['id'], unique=False)
    op.create_table('prediction_market_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('yes', 'no', name='predictionmarketoutcome'), nullable=False),
    sa.Column('shares_held', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('average_cost_per_share', sa.Float(), nullable=False),
    sa.Column('position_status', sa.Enum('open', 'closed', 'settled', name='predictionpositionstatus'), nullable=False),
    sa.Column('settled_payout', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['prediction_markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_market_positions_id'), 'prediction_market_positions', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_market_positions_market_id'), 'prediction_market_positions', ['market_id'], unique=False)
    op.create_index(op.f('ix_prediction_market_positions_user_id'), 'prediction_market_positions', ['user_id'], unique=False)
    op.create_table('prediction_market_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.Enum('buy', 'sell', name='predictiontradetype'), nullable=False),
    sa.Column('side', sa.Enum('yes', 'no', name='predictionmarketoutcome'), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('kes_amount', sa.Float(), nullable=False),
    sa.Column('yes_price_at_trade', sa.Float(), nullable=False),
    sa.Column('q_yes_after', sa.Float(), nullable=False),
    sa.Column('q_no_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['prediction_markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_market_trades_id'), 'prediction_market_trades', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_market_trades_market_id'), 'prediction_market_trades', ['market_id'], unique=False)
    op.create_index(op.f('ix_prediction_market_trades_user_id'), 'prediction_market_trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_market_trades_user_id'), table_name='prediction_market_trades')
    op.drop_index(op.f('ix_prediction_market_trades_market_id'), table_name='prediction_market_trades')
    op.drop_index(op.f('ix_prediction_market_trades_id'), table_name='prediction_market_trades')
    op.drop_table('prediction_market_trades')
    op.drop_index(op.f('ix_prediction_market_positions_user_id'), table_name='prediction_market_positions')
    op.drop_index(op.f('ix_prediction_market_positions_market_id'), table_name='prediction_market_positions')
    op.drop_index(op.f('ix_prediction_market_positions_id'), table_name='prediction_market_positions')
    op.drop_table('prediction_market_positions')
    op.drop_index(op.f('ix_prediction_markets_id'), table_name='prediction_markets')
    op.drop_table('prediction_markets')
    # ### end Alembic commands ###
