"""empty message

Revision ID: ae965fea1bf5
Revises: 1ff6e719a156
Create Date: 2026-05-08 08:49:47.528686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae965fea1bf5'
down_revision: Union[str, Sequence[str], None] = '1ff6e719a156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_markets', sa.Column('resolution_criteria', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_markets', 'resolution_criteria')
    # ### end Alembic commands ###
