"""empty message

Revision ID: d3413bfca2d4
Revises: 
Create Date: 2025-07-12 23:05:08.127020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3413bfca2d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'country_code') THEN
            CREATE TYPE country_code AS ENUM ('KE');
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'account_status_code') THEN
            CREATE TYPE account_status_code AS ENUM ('basic');
        END IF;
    END
    $$;
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop enum types (they will be automatically dropped when no longer in use)
    op.execute("""
    DROP TYPE IF EXISTS account_status_code CASCADE;
    DROP TYPE IF EXISTS country_code CASCADE;
    """)
    # ### end Alembic commands ###
