"""empty message

Revision ID: d6bf4c825a4e
Revises: 5791d46bcf9a
Create Date: 2026-04-12 21:34:46.357988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6bf4c825a4e'
down_revision: Union[str, Sequence[str], None] = '5791d46bcf9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_based_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('b', sa.Float(), nullable=False),
    sa.Column('q_home', sa.Float(), nullable=False),
    sa.Column('q_draw', sa.Float(), nullable=False),
    sa.Column('q_away', sa.Float(), nullable=False),
    sa.Column('total_collected', sa.Float(), nullable=False),
    sa.Column('house_reserve', sa.Float(), nullable=False),
    sa.Column('market_status', sa.Enum('pending_approval', 'active', 'locked', 'resolved', 'rejected', 'cancelled', name='fixturebasedmarketstatus'), nullable=False),
    sa.Column('locks_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_date', sa.DateTime(), nullable=True),
    sa.Column('resolution_source', sa.String(), nullable=True),
    sa.Column('outcome', sa.Enum('home', 'draw', 'away', name='fixturebasedmarketoutcome'), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.local_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_based_markets_fixture_id'), 'fixture_based_markets', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_fixture_based_markets_id'), 'fixture_based_markets', ['id'], unique=False)
    op.create_table('fixture_based_market_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('home', 'draw', 'away', name='fixturebasedmarketoutcome'), nullable=False),
    sa.Column('shares_held', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('average_cost_per_share', sa.Float(), nullable=False),
    sa.Column('position_status', sa.Enum('open', 'closed', 'settled', name='fixturebasedpositionstatus'), nullable=False),
    sa.Column('settled_payout', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['fixture_based_markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_based_market_positions_id'), 'fixture_based_market_positions', ['id'], unique=False)
    op.create_index(op.f('ix_fixture_based_market_positions_market_id'), 'fixture_based_market_positions', ['market_id'], unique=False)
    op.create_index(op.f('ix_fixture_based_market_positions_user_id'), 'fixture_based_market_positions', ['user_id'], unique=False)
    op.create_table('fixture_based_market_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.Enum('buy', 'sell', name='fixturebasedtradetype'), nullable=False),
    sa.Column('side', sa.Enum('home', 'draw', 'away', name='fixturebasedmarketoutcome'), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('kes_amount', sa.Float(), nullable=False),
    sa.Column('home_price_at_trade', sa.Float(), nullable=False),
    sa.Column('draw_price_at_trade', sa.Float(), nullable=False),
    sa.Column('away_price_at_trade', sa.Float(), nullable=False),
    sa.Column('q_home_after', sa.Float(), nullable=False),
    sa.Column('q_draw_after', sa.Float(), nullable=False),
    sa.Column('q_away_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['fixture_based_markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_based_market_trades_id'), 'fixture_based_market_trades', ['id'], unique=False)
    op.create_index(op.f('ix_fixture_based_market_trades_market_id'), 'fixture_based_market_trades', ['market_id'], unique=False)
    op.create_index(op.f('ix_fixture_based_market_trades_user_id'), 'fixture_based_market_trades', ['user_id'], unique=False)
    op.add_column('fixtures', sa.Column('prediction_market_created', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'prediction_market_created')
    op.drop_index(op.f('ix_fixture_based_market_trades_user_id'), table_name='fixture_based_market_trades')
    op.drop_index(op.f('ix_fixture_based_market_trades_market_id'), table_name='fixture_based_market_trades')
    op.drop_index(op.f('ix_fixture_based_market_trades_id'), table_name='fixture_based_market_trades')
    op.drop_table('fixture_based_market_trades')
    op.drop_index(op.f('ix_fixture_based_market_positions_user_id'), table_name='fixture_based_market_positions')
    op.drop_index(op.f('ix_fixture_based_market_positions_market_id'), table_name='fixture_based_market_positions')
    op.drop_index(op.f('ix_fixture_based_market_positions_id'), table_name='fixture_based_market_positions')
    op.drop_table('fixture_based_market_positions')
    op.drop_index(op.f('ix_fixture_based_markets_id'), table_name='fixture_based_markets')
    op.drop_index(op.f('ix_fixture_based_markets_fixture_id'), table_name='fixture_based_markets')
    op.drop_table('fixture_based_markets')
    # ### end Alembic commands ###
