"""empty message

Revision ID: e0ce5caefea0
Revises: 54408348aafe
Create Date: 2026-04-04 23:56:57.115588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ce5caefea0'
down_revision: Union[str, Sequence[str], None] = '54408348aafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool_stake_entries', 'possible_win')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool_stake_entries', sa.Column('possible_win', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
