"""empty message

Revision ID: ed8722ff1f1c
Revises: f0a783297172
Create Date: 2026-02-11 16:41:57.357293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8722ff1f1c'
down_revision: Union[str, Sequence[str], None] = 'f0a783297172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('season_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fixtures', 'seasons', ['season_id'], ['local_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fixtures', type_='foreignkey')
    op.drop_column('fixtures', 'season_id')
    # ### end Alembic commands ###
