"""empty message

Revision ID: f0a783297172
Revises: 1f0e4990e927
Create Date: 2026-02-11 16:30:23.310053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a783297172'
down_revision: Union[str, Sequence[str], None] = '1f0e4990e927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('leagues_season_id_fkey'), 'leagues', type_='foreignkey')
    op.drop_column('leagues', 'season_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('season_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('leagues_season_id_fkey'), 'leagues', 'seasons', ['season_id'], ['local_id'])
    # ### end Alembic commands ###
