"""empty message

Revision ID: fd0e461dba04
Revises: c800f181476b
Create Date: 2025-07-06 01:44:11.467273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0e461dba04'
down_revision: Union[str, Sequence[str], None] = 'c800f181476b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('description', sa.Text(), nullable=False))
    op.drop_column('routines', 'descriptin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('descriptin', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('routines', 'description')
    # ### end Alembic commands ###
